version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fitz
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/todo
    depends_on:
      - db
